"use server";

export async function greetUser(name: string) {
  // Simulate server processing
  await new Promise((resolve) => setTimeout(resolve, 500));

  return `Hello, ${name}! This greeting was generated by a server action.`;
}
